name: Deploy digital-twin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [closed]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DEPLOY_PASS: ${{ secrets.DEPLOY_PASSWORD }}
      REMOTE_DIR: "/opt/1panel/apps/openresty/openresty/www/sites/digital-twin.hub.feashow.cn/index"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Set pnpm to use Taobao registry
        run: pnpm config set registry https://registry.npmmirror.com

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build

      - name: Verify dist directory
        run: |
          if [ ! -d "dist" ]; then
            echo "::error::Build directory 'dist' not found after build!"
            exit 1
          fi
          echo "✓ Build successful"

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass rsync
          echo "工具安装完成"
          
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile /dev/null" > ~/.ssh/config

      - name: Rsync deployment
        run: |
          echo "=== 同步build文件到/index目录 ==="
          echo "源路径: $(pwd)/build"
          echo "目标路径: ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:$REMOTE_DIR"
          
          sshpass -p "$DEPLOY_PASS" rsync -avz --delete --stats \
            -e "ssh -p ${{ secrets.SSH_PORT }}" \
            build/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:$REMOTE_DIR/ \
            | tee rsync.log

          if [ $? -ne 0 ]; then
            echo "::error::同步失败"
            grep -i "error\|fail" rsync.log || echo "未发现具体错误"
            exit 1
          fi

          echo "=== 同步结果 ==="
          grep "Number of files" rsync.log || echo "无统计信息"
          echo "目标目录大小: $(sshpass -p "$DEPLOY_PASS" ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "du -sh $REMOTE_DIR")"
